### PR TITLE
Task 12 CORE-Error-handling

### PR DESCRIPTION
**Pull request by filosoho**

### CODE REVIEW

**Comment by nc-niamh-smith** [comment]
So you've made a really nice error handler for any wrong endpoint, but going through your site, it looks like when I click on an article, there's nothing in the URL bar any more - meaning I couldn't send it to someone else if I wanted to! 

Have a look into how you could change that - ideally on the SingleArticle page the URL should end with /articles/:article_id :)

**Comment by filosoho** [comment]
Hi Niamh, thank you for your feedback! I am not sure if I understand what does it mean ' when I click on an article, there's nothing in the URL bar any more - meaning I couldn't send it to someone else if I wanted to!', could you please explain? On my end if I click on an article it shows in the URL for example this:  http://localhost:5173/article/34 and if I paste it on another tab when the application is running - it takes me to that specific article.

**Comment by nc-niamh-smith** [comment]
Ah! I was doing articles with an 's' instead of 'article/34'! It's absolutely fine your way instead :)

**Comment by filosoho** [comment]
Thank you for looking into this Niamh! Glad it's all working! 🙌🏼 😊

**Pull request merged**
